apiVersion: perses.dev/v1alpha1
kind: PersesDatasource
metadata:
  name: user-defined-monitoring
  namespace: example-team
spec:
  config:
    default: true
    display:
      name: "User-defined Monitoring (example-team)"
    plugin:
      kind: "PrometheusDatasource"
      spec:
        proxy:
          kind: HTTPProxy
          spec:
            url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092?namespace=example-team
            secret: user-defined-monitoring-secret
            client:
              tls:
                enable: true
                caCert:
                  type: file
                  certPath: /ca/service-ca.crt
