apiVersion: perses.dev/v1alpha1
kind: PersesDatasource
metadata:
  name: user-defined-monitoring
  namespace: ai-performance-profiling
spec:
  client:
    tls:
      enable: true
      caCert:
        type: file
        certPath: /ca/service-ca.crt
  config:
    default: true
    display:
      name: "ai-performance-profiling datasource"
    plugin:
      kind: "PrometheusDatasource"
      spec:
        proxy:
          kind: HTTPProxy
          spec:
            url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092?namespace=ai-performance-profiling
            secret: user-defined-monitoring-secret
